Fix flakey TestRoomKeyIsCycledAfterEnoughTime
Tests could fail with:
```
  thread 'tokio-runtime-worker' panicked at /home/runner/work/matrix-rust-sdk/matrix-rust-sdk/crates/matrix-sdk-crypto/src/session_manager/group_sessions.rs:211:9:
  Session expired
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Due to this assertion being violated: `assert!(!session.expired(), "Session expired");`.

My guess is that the code does something like:
 - check if expired session
 - if expired, then renew it
 - encrypt message, after first asserting that we are using a valid session

This is unsafe, as it's effectively a read-modify-write race condition, since
the session can expire due to time i.e the first check passes because it will
expire in 1 nanosecond, then the assertion fails when encrypting.

Also repoint `install_uniffi_bindgen_go.sh` to upstream.