bugfix: fix a random crash in FFI code.
The crash would confusingly happen in other tests, sometimes
even JS tests! This was because I forgot to clean up some FFI
objects. Go's GC would eventually deallocate the matching Go object
which then automatically calls `.Destroy()` on the FFI object.

However, if this ran sufficiently late then the supporting Tokio
runtime may no longer exist, meaning rust code cannot use async/await.
This would cause a panic with:

> thread '<unnamed>' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime'